### PR TITLE
Avoid possible GC allocations in MongoCursor.~this

### LINKED ISSUE #2793: Error on creating a mongo connection
Hey everyone, I just updated my project to use the latest vibe version and I started getting this exception. Does anyone have an idea on how I could debug it?

```
creating new MongoConnection connection, all 1 are in use
TaskFiber getting terminated due to an uncaught core.exception.InvalidMemoryOperationError
core.exception.InvalidMemoryOperationError@core/lifetime.d(126): Invalid memory operation
----------------
??:? onInvalidMemoryOperationError [0x7f5d2016a83d]
??:? nothrow void* core.internal.gc.impl.conservative.gc.ConservativeGC.runLocked!(core.internal.gc.impl.conservative.gc.ConservativeGC.mallocNoSync(ulong, uint, ref ulong, const(TypeInfo)), core.internal.gc.impl.conservative.gc.mallocTime, core.internal.gc.impl.conservative.gc.numMallocs, ulong, uint, ulong, const(TypeInfo)).runLocked(ref ulong, ref uint, ref ulong, ref const(TypeInfo)) [0x7f5d2017a023]
??:? _DThn16_4core8internal2gc4impl12conservativeQw14ConservativeGC6mallocMFNbmkxC8TypeInfoZPv [0x7f5d2017d1a4]
../../../../.dub/packages/vibe-d/0.10.0/vibe-d/mongodb/vibe/db/mongo/client.d:66 [0xe55eef]
../../../../.dub/packages/vibe-core/2.8.2/vibe-core/source/vibe/core/connectionpool.d:94 [0xe568ad]
../../../../.dub/packages/vibe-d/0.10.0/vibe-d/mongodb/vibe/db/mongo/client.d:167 [0xe5600f]
../../../../.dub/packages/vibe-d/0.10.0/vibe-d/mongodb/vibe/db/mongo/cursor.d:518 [0x809d34]
../../../../.dub/packages/vibe-d/0.10.0/vibe-d/mongodb/vibe/db/mongo/cursor.d:124 [0x4e4a4d]
submodules/crate/source/crate/resource/gridfs.d:481 [0xb9e308]
??:? rt_finalize2 [0x7f5d201a4556]
??:? nothrow ulong core.internal.gc.impl.conservative.gc.Gcx.sweep() [0x7f5d2018034e]
??:? nothrow ulong core.internal.gc.impl.conservative.gc.Gcx.fullcollect(bool, bool, bool) [0x7f5d2017c6f9]
??:? nothrow void* core.internal.gc.impl.conservative.gc.Gcx.bigAlloc(ulong, ref ulong, uint, const(TypeInfo)) [0x7f5d2017f143]
??:? nothrow void* core.internal.gc.impl.conservative.gc.ConservativeGC.runLocked!(core.internal.gc.impl.conservative.gc.ConservativeGC.mallocNoSync(ulong, uint, ref ulong, const(TypeInfo)), core.internal.gc.impl.conservative.gc.mallocTime, core.internal.gc.impl.conservative.gc.numMallocs, ulong, uint, ulong, const(TypeInfo)).runLocked(ref ulong, ref uint, ref ulong, ref const(TypeInfo)) [0x7f5d2017a058]
??:? _DThn16_4core8internal2gc4impl12conservativeQw14ConservativeGC6qallocMFNbmkMxC8TypeInfoZSQDd6memory8BlkInfo_ [0x7f5d2017d232]
??:? gc_qalloc [0x7f5d2018683b]
??:? core.memory.BlkInfo_const  rt.lifetime.__arrayAlloc(ulong, ref core.memory.BlkInfo_const , TypeInfo, const(TypeInfo)) [0x7f5d201a28fb]
??:? _d_arraysetlengthiT [0x7f5d201a5adc]
/usr/lib/ldc/x86_64-redhat-linux-gnu/include/d/core/internal/array/capacity.d:47 [0x80a71a]
../../../../.dub/packages/vibe-d/0.10.0/vibe-d/mongodb/vibe/db/mongo/cursor.d:533 [0x80a6c3]
../../../../.dub/packages/vibe-d/0.10.0/vibe-d/mongodb/vibe/db/mongo/connection.d:600 [0x80f304]
../../../../.dub/packages/vibe-d/0.10.0/vibe-d/mongodb/vibe/db/mongo/connection.d:752 [0x4f7672]
source/ogm/api/api.d:590 [0x80ad28]
../../../../.dub/packages/vibe-d/0.10.0/vibe-d/mongodb/vibe/db/mongo/connection.d:520 [0x80a38b]
source/ogm/api/api.d:464 [0x809a6c]
../../../../.dub/packages/vibe-d/0.10.0/vibe-d/mongodb/vibe/db/mongo/cursor.d:137 [0x4e4c04]
/usr/lib/ldc/x86_64-redhat-linux-gnu/include/d/std/range/primitives.d:1788 [0xb2836c]
submodules/crate/source/crate/base.d:732 [0xb282e6]
submodules/crate/source/crate/resource/gridfs.d:507 [0xb9e3f9]
source/ogm/api/service.d:82 [0x4ce8d3]
../../../../.dub/packages/vibe-core/2.8.2/vibe-core/source/vibe/core/task.d:780 [0x8115be]
../../../../.dub/packages/vibe-core/2.8.2/vibe-core/source/vibe/core/task.d:798 [0xf9590b]
../../../../.dub/packages/vibe-core/2.8.2/vibe-core/source/vibe/core/task.d:471 [0xf95129]
../../../../.dub/packages/vibe-core/2.8.2/vibe-core/source/vibe/core/task.d:411 [0xf94c7d]
??:? fiber_entryPoint [0x7f5d201911ea]
Error Program exited with code -6

```

### PR DESCRIPTION
**Pull request by s-ludwig**
This adds a check to the destructor to avoid running into an InvalidMemoryOperationError and instead outputs a more descriptive error message without crashing. This also swaps back the order of operations in killCursors() so that no connection to the server gets allocated by the call if the cursor has already been killed.

Fixes #2793.

### CODE REVIEW

File: mongodb/vibe/db/mongo/cursor.d [hunk 1]
```diff
@@ -119,12 +119,26 @@ struct MongoCursor(DocType = Bson) {
...
-				logDiagnostic("%s", (() @trusted => e.toString)());
+		import core.memory : GC;
+
+		if (m_data && --m_data.refCount == 0) {
+			if (m_data.alive) {
+				// avoid InvalidMemoryOperation errors in case the cursor was
+				// leaked to the GC
+				if(GC.inFinalizer) {
+					logError("MongoCursor instance that has not been fully processed leaked to the GC!");
+					try throw new Exception("");
```
Comment (WebFreak001) [inline mongodb/vibe/db/mongo/cursor.d:130]: this is an allocation, is this even reliable? Might need to check the ABI docs here

Comment (s-ludwig) [reply mongodb/vibe/db/mongo/cursor.d:130]: Oops, you are right of course, that won't work, I didn't really think there. Unfortunate that we don't have `@nogc` stack trace code in DRuntime. I do have an implementation for a different project, maybe it makes sense to publish that on code.dlang.org.

Comment (WebFreak001) [reply mongodb/vibe/db/mongo/cursor.d]: so I'm not even sure if the definition is exactly not to allocate in a destructor, since it's not listed in the spec: https://dlang.org/spec/class.html#destructors

however it says not to use child data - unsure how it's supposed to work with cyclic things

**Review by WebFreak001 — APPROVED** [review]

File: mongodb/vibe/db/mongo/cursor.d (hunk 1 above)
Comment (s-ludwig) [reply mongodb/vibe/db/mongo/cursor.d]: The reality with the GC is that finalizers (or struct destructors in that situation) are only (safely) usable for very simple things (calling `free()` or `close()`). It's also not just child data, but also any GC allocated memory that poses a problem (i.e. data referenced by static variables). I'm not sure if or where it's mentioned in the spec, but the implementation will error out for any GC action you invoke from within a finalizer call.

While some of this could definitely improved in the GC, I think the only realistic way to avoid issues like this is to make eventcore and the relevant parts of vibe-core fully `@nogc`.

BTW, another serious shortcoming with the current GC is that you also may only do thread-safe things, so even something like `glDeleteTextures()` is not an option, and since finalizers are running in parallel to application code, I bet that there are many race-conditions hidden in real-world finalizers.
